### ISSUE TITLE
Includes through url not working

### ISSUE THREAD

**Issue by MartijnThomas** [appkr/fractal#5]
Great package!

I'm trying to include a relationship through the url, but it does not work. Eg. http://api.example.com/v1/resource?include=something

I use the Trait (`Appkr\Fractal\Http\ApiResponse`), is it possible that this does not work with the Trait? Or do I need to configure more?

To let you know, if I add `something` to the defaultInclude array, the relation is successfully loaded.

**Comment by appkr** [comment]
@MartijnThomas I'm tied up at the moment. I promise I'll get back to  you as soon as I finish the work in my hand.

**Comment by appkr** [comment]
@MartijnThomas My original intention was, like `setMeta()` method, you chain the `setIncludes()` in your controller. Something like `$this->respond->setInclude(Request::input('include'))->withPagination(...)`.

But in response to your request, I put it in the Response class, and will be working out of the box. I hope it satisfy your needs.

**`Note`**  You have to define `$availableIncludes` array and `includeSomething()` method in your transformer so that the inclusion work with url parameter.

**Comment by MartijnThomas** [comment]
Awesome man! I'll check this out later today!

Yeah I know that I have to define the includes, it worked fine for the default include.

If there is something, I let you know :)
